Repository rubrikinc/rubrik-sdk-for-powershell, pull requests merged in 2019-11, with the labels that each got.

#492 Issue 487 - Expose volume letter in "Get-RubrikVolumeGroup"
  CHANGELOG.md
  Rubrik/ObjectDefinitions/Rubrik.VolumeGroup.ps1xml
  Rubrik/Public/Get-RubrikVolumeGroup.ps1
  Tests/Get-RubrikVolumeGroup.Tests.ps1
Labels: area-rcdm, exp-intermediate, kind-enhancement

#499 Issue 478 - fix primary_cluster_id documenation
  CHANGELOG.md
  Rubrik/Public/Get-RubrikVApp.ps1
  Rubrik/Public/Get-RubrikVolumeGroup.ps1
Labels: area-rcdm, exp-beginner, kind-docs

#501 Updated Contributing.md - Use Devel instead of Master
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: area-rcdm, exp-beginner, kind-docs, kind-enhancement, priority-p1

#502 Separate bash scripts into different files - Issue #483
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/PULL_REQUEST_TEMPLATE.md
  azure-pipelines/azure-pipelines-devel-merge.yml
  azure-pipelines/azure-pipelines-master-merge.yml
  azure-pipelines/scripts/git-check-skipci.sh
  azure-pipelines/scripts/git-devel-merge.sh
  azure-pipelines/scripts/git-master-merge.sh
  azure-pipelines/scripts/install.ps1
  workflows/Test-RubrikBackupValidation.ps1
Labels: area-rcdm, exp-intermediate, kind-bug, kind-docs, priority-p1

#508 Update User Agent string to provide additional information
  CHANGELOG.md
  Rubrik/Private/New-UserAgentString.ps1
  Rubrik/Public/Connect-Rubrik.ps1
  Rubrik/Rubrik.psd1
  Tests/New-UserAgentString.Tests.ps1
Labels: area-rcdm, exp-expert, kind-enhancement, priority-p1

#513 Add logic to pull from remote cluster ID
  CHANGELOG.md
  Rubrik/Private/Test-RubrikSLA.ps1
  Rubrik/Public/Get-RubrikVM.ps1
  Rubrik/Rubrik.psd1
Labels: area-rcdm, exp-expert, kind-enhancement, priority-p1
