Repository rubrikinc/rubrik-sdk-for-powershell, pull requests merged in 2019-07, with the labels that each got.

#331 Updated $null = to Out-Null for PowerShell 6 Performance improvements
  CHANGELOG.md
  Rubrik/Private/New-BodyString.ps1
  Rubrik/Private/Submit-Request.ps1
  Rubrik/Public/Move-RubrikMountVMDK.ps1
  Rubrik/Public/Sync-RubrikAnnotation.ps1
Labels: area-rcdm, exp-beginner, kind-enhancement

#356 Issue 333 Add Unit Tests for Export-RubrikDatabase and Export-RubrikReport
  CHANGELOG.md
  Rubrik/Public/Export-RubrikDatabase.ps1
  Tests/Export-RubrikDatabase.Tests.ps1
  Tests/Export-RubrikReport.Tests.ps1
Labels: area-rcdm, exp-intermediate, kind-enhancement, priority-p2

#359 Unit tests for Virtual Machine functions
  CHANGELOG.md
  Rubrik/Public/Get-RubrikHyperVVM.ps1
  Rubrik/Public/Get-RubrikNutanixVM.ps1
  Rubrik/Public/New-RubrikVMDKMount.ps1
  Rubrik/Public/Protect-RubrikHyperVVM.ps1
  Rubrik/Public/Protect-RubrikNutanixVM.ps1
  Rubrik/Public/Protect-RubrikVM.ps1
  Rubrik/Public/Set-RubrikHyperVVM.ps1
  Rubrik/Public/Set-RubrikNutanixVM.ps1
  Rubrik/Public/Set-RubrikVM.ps1
  Tests/Get-RubrikHyperVVM.Tests.ps1
  Tests/Get-RubrikNutanixVM.Tests.ps1
  Tests/Move-RubrikMountVMDK.Tests.ps1
  Tests/New-RubrikVMDKMount.Tests.ps1
  Tests/Protect-RubrikHyperVVM.Tests.ps1
  Tests/Protect-RubrikNutanixVM.Tests.ps1
  Tests/Protect-RubrikVM.Tests.ps1
  Tests/Set-RubrikHyperVVM.Tests.ps1
  Tests/Set-RubrikNutanixVM.Tests.ps1
  Tests/Set-RubrikVM.Tests.ps1
Labels: area-rcdm, exp-intermediate, kind-enhancement

#357 Get-RubrikDatabase - Change in behavior of switch param - Issue #303
  CHANGELOG.md
  Rubrik/Private/Test-QueryObject.ps1
  Rubrik/Public/Get-RubrikDatabase.ps1
Labels: area-rcdm, exp-expert, kind-enhancement

#355 Fix internal JSON parser - Remove Newtonsoft requirement - Issue #288
  CHANGELOG.md
  Rubrik/Private/Format-JSON.ps1
  Rubrik/Private/Newtonsoft.Json.dll
  Rubrik/Private/Submit-Request.ps1
  Tests/Submit-Request.Tests.ps1
Labels: area-rcdm, exp-expert, kind-bug, kind-enhancement

#328 PF - Issue #283
  CHANGELOG.md
  Rubrik/Private/Get-RubrikAPIData.ps1
  Rubrik/Public/Set-RubrikSLA.ps1
  Rubrik/Rubrik.psd1
Labels: area-rcdm, exp-expert, kind-enhancement

#373 Implement Powershell BootStrap Functions
  Rubrik/Private/Get-RubrikAPIData.ps1
  Rubrik/Private/New-BodyString.ps1
  Rubrik/Public/Get-RubrikBootStrap.ps1
  Rubrik/Public/Get-RubrikHost.ps1
  Rubrik/Public/New-RubrikBootStrap.ps1
  Rubrik/Rubrik.psd1
  templates/Bootstrap-Rubrik.ps1
  templates/Bootstrap-RubrikEdge.ps1
Labels: area-rcdm, kind-enhancement, priority-p1

#379 Change output type of http status code in Submit-Request - Issue 377
  CHANGELOG.md
  Rubrik/Private/Invoke-RubrikWebRequest.ps1
  Rubrik/Private/New-BodyString.ps1
  Rubrik/Private/Submit-Request.ps1
  Tests/Submit-Request.Tests.ps1
Labels: area-rcdm, exp-beginner, kind-enhancement, priority-p2

#380 Add Token validation for Connect-Rubrik - Issue 374
  CHANGELOG.md
  Rubrik/Public/Connect-Rubrik.ps1
  Rubrik/Public/Get-RubrikAPIToken.ps1
Labels: area-rcdm, exp-intermediate, kind-enhancement, priority-p1

#385 Improvements in Connect-Rubrik
  CHANGELOG.md
  Rubrik/Public/Connect-Rubrik.ps1
Labels: area-rcdm, exp-beginner, kind-enhancement

#388 Unit tests for Database functions
  CHANGELOG.md
  Rubrik/Public/Get-RubrikDatabase.ps1
  Rubrik/Public/Get-RubrikDatabaseFiles.ps1
  Rubrik/Public/Get-RubrikDatabaseRecoverableRange.ps1
  Rubrik/Public/New-RubrikDatabaseMount.ps1
  Rubrik/Public/Protect-RubrikDatabase.ps1
  Rubrik/Public/Remove-RubrikDatabaseMount.ps1
  Rubrik/Public/Restore-RubrikDatabase.ps1
  Rubrik/Public/Set-RubrikDatabase.ps1
  Rubrik/Public/Set-RubrikSQLInstance.ps1
  Tests/Get-RubrikDatabase.Tests.ps1
  Tests/Get-RubrikDatabaseFiles.Tests.ps1
  Tests/Get-RubrikDatabaseMount.Tests.ps1
  Tests/Get-RubrikDatabaseRecoverableRange.Tests.ps1
  Tests/Get-RubrikSQLInstance.Tests.ps1
  Tests/New-RubrikDatabaseMount.Tests.ps1
  Tests/Protect-RubrikDatabase.Tests.ps1
  Tests/Remove-RubrikDatabaseMount.Tests.ps1
  Tests/Restore-RubrikDatabase.Tests.ps1
  Tests/Set-RubrikDatabase.Tests.ps1
  Tests/Set-RubrikSQLInstance.Tests.ps1
Labels: area-rcdm, exp-beginner, kind-enhancement

#392 Add support for allowed backup windows in New-RubrikSLA
  CHANGELOG.md
  Rubrik/Private/Get-RubrikAPIData.ps1
  Rubrik/Public/New-RubrikSLA.ps1
Labels: area-rcdm, exp-expert, kind-enhancement, priority-p1

#395 Resolve Oracle DB Snapshot issue #394
  CHANGELOG.md
  Rubrik/Private/Get-RubrikAPIData.ps1
Labels: area-rcdm, exp-beginner, kind-bug

#396 Get-RubrikSnapshot fails on Filesets Issue #393
  CHANGELOG.md
  Rubrik/Public/Get-RubrikFileset.ps1
  Rubrik/Public/Get-RubrikSnapshot.ps1
Labels: area-rcdm, exp-expert, kind-enhancement, priority-p1

#398 Fixed: Get-RubrikEvent submits 2 limit flags issue 353
  CHANGELOG.md
  Rubrik/Private/Test-QueryParam.ps1
  Rubrik/Public/New-RubrikSLA.ps1
Labels: area-rcdm, exp-expert, kind-bug, priority-p2

#412 Documentation in readme.md is out of date - Issue #411
  CHANGELOG.md
  README.md
Labels: area-rcdm, exp-beginner, kind-docs, priority-p1

#413 Issue with Get-RubrikSQLInstance and documentation update - Issue #399
  CHANGELOG.md
  Rubrik/Private/Get-RubrikAPIData.ps1
  Rubrik/Public/Get-RubrikSQLInstance.ps1
Labels: area-rcdm, exp-expert, kind-bug, kind-docs, priority-p1
