Repository rubrikinc/rubrik-sdk-for-powershell, pull requests merged in 2019-10, with the labels that each got.

#444 Issue 349 - Get-RubrikObject
  CHANGELOG.md
  Rubrik/Public/Get-RubrikObject.ps1
  Rubrik/Rubrik.psd1
  Tests/Get-RubrikAPIData.Tests.ps1
  Tests/Get-RubrikObject.Tests.ps1
Labels: kind-enhancement

#486 Case sensitivity for PrimaryClusterId, Issue #469
  CHANGELOG.md
  Rubrik/Private/Test-QueryObject.ps1
  Rubrik/Private/Test-QueryParam.ps1
Labels: area-rcdm, exp-beginner, kind-bug

#490 Update README.md
  README.md
Labels: kind-bug, kind-docs, priority-p0
