Repository rubrikinc/rubrik-sdk-for-powershell, pull requests merged in 2019-06, with the labels that each got.

#300 Add -ApplicationTag parameter to New-RubrikManagedVolume
  CHANGELOG.md
  Rubrik/Private/Get-RubrikAPIData.ps1
  Rubrik/Public/New-RubrikManagedVolume.ps1
  docs/reference/New-RubrikManagedVolume.md
  docs/reference/Remove-RubrikManagedVolume.md
Labels: area-rcdm, exp-expert, kind-enhancement

#275 Fixes in New-RubrikVMDKMount.ps1
  CHANGELOG.md
  Rubrik/Public/New-RubrikMount.ps1
  Rubrik/Public/New-RubrikVMDKMount.ps1
Labels: area-rcdm, exp-beginner, kind-bug

#306 Add new cmdlet Update-RubrikVMwareVM
  CHANGELOG.md
  Rubrik/Private/Get-RubrikAPIData.ps1
  Rubrik/Public/Update-RubrikVMwareVM.ps1
  Rubrik/Rubrik.psd1
  Tests/Update-RubrikVMwareVM.Tests.ps1
Labels: area-rcdm, exp-intermediate, kind-docs

#308 Add Remove-RubrikVMSnapshot cmdlet and additional logging
  CHANGELOG.md
  Rubrik/Private/Get-RubrikAPIData.ps1
  Rubrik/Private/Invoke-RubrikWebRequest.ps1
  Rubrik/Private/Submit-Request.ps1
  Rubrik/Public/Remove-RubrikVMSnapshot.ps1
  Rubrik/Rubrik.psd1
  Tests/Remove-RubrikVMSnapshot.Tests.ps1
Labels: area-rcdm, exp-expert, kind-enhancement

#301 Created Set-RubrikVolumeFilterDriver (Issue 291), Added DetailedObject to Get-RubrikHost
  CHANGELOG.md
  Rubrik/Private/Get-RubrikAPIData.ps1
  Rubrik/Public/Get-RubrikHost.ps1
  Rubrik/Public/Set-RubrikVolumeFilterDriver.ps1
  Rubrik/Rubrik.psd1
Labels: area-rcdm, exp-expert, kind-enhancement

#317 New API Token cmdlets
  CHANGELOG.md
  Rubrik/Private/Get-RubrikAPIData.ps1
  Rubrik/Public/New-RubrikAPIToken.ps1
  Rubrik/Public/Remove-RubrikAPIToken.ps1
  Rubrik/Rubrik.psd1
  Tests/Get-RubrikAPIData.Tests.ps1
  Tests/Get-RubrikVM.Tests.ps1
  Tests/New-RubrikAPIToken.Tests.ps1
  Tests/Remove-RubrikAPIToken.Tests.ps1
Labels: area-rcdm

#266 Oracle Database support in Rubrik SDK for PowerShell
  CHANGELOG.md
  Rubrik/Private/Get-RubrikAPIData.ps1
  Rubrik/Private/Test-QueryParam.ps1
  Rubrik/Public/Get-RubrikOracleDB.ps1
  Rubrik/Rubrik.psd1
  Tests/Get-RubrikOracleDB.Tests.ps1
  Tests/New-RubrikSnapshot.Tests.ps1
Labels: kind-feature

#322 Added Get-RubrikAPIToken cmdlet
  CHANGELOG.md
  Rubrik/Private/Get-RubrikAPIData.ps1
  Rubrik/Public/Get-RubrikAPIToken.ps1
  Rubrik/Rubrik.psd1
  Tests/Get-RubrikAPIToken.Tests.ps1
Labels: area-rcdm, exp-intermediate, kind-enhancement

#320 Issue 319 - DetailedObject support for older versions of Powershell
  CHANGELOG.md
  Rubrik/Private/Get-RubrikAPIData.ps1
  Rubrik/Public/Get-RubrikHost.ps1
  Rubrik/Public/Get-RubrikOracleDB.ps1
  Rubrik/Public/Get-RubrikVM.ps1
  Tests/Get-RubrikHost.Tests.ps1
Labels: area-rcdm, exp-beginner, kind-bug

#324 Updated Sync-RubrikAnnotation to include latest snapshot and added unit tests
  CHANGELOG.md
  Rubrik/Public/Sync-RubrikAnnotation.ps1
  Tests/Sync-RubrikAnnotation.Tests.ps1
Labels: area-rcdm, exp-expert, kind-bug

#290 Adding a Get-RubrikEvent function for issue #289
  Rubrik/Private/Get-RubrikAPIData.ps1
  Rubrik/Public/Get-RubrikEvent.ps1
  Rubrik/Rubrik.psd1
  Tests/Get-RubrikEvent.Tests.ps1
  docs/CHANGELOG.md
Labels: area-rcdm, exp-intermediate, kind-enhancement

#313 Initial outline of offline usage of module
  CHANGELOG.md
  docs/quick-start.md
Labels: exp-beginner, kind-docs

#330 Added additional examples to New-RubrikSnapshot
  CHANGELOG.md
  Rubrik/Private/ConvertFrom-LocalDate.ps1
  Rubrik/Private/Format-JSON.ps1
  Rubrik/Public/New-RubrikSnapshot.ps1
Labels: area-rcdm, exp-beginner, kind-docs
