Repository rubrikinc/rubrik-sdk-for-powershell, pull requests merged in 2019-01, with the labels that each got.

#225 README updates for the new repo name
  README.md
Labels: kind-docs

#230 Updates to Get/New/Remove-RubrikSLA for new v2 API endpoint
  Rubrik/Private/Get-RubrikAPIData.ps1
  Rubrik/Public/New-RubrikSLA.ps1
Labels: kind-enhancement

#227 Pierre Flammer: Added VolumeGroup functionality
  Rubrik/Get-RubrikAPIData.ps1
  Rubrik/Private/Get-RubrikAPIData.ps1
  Rubrik/Private/Test-QueryParam.ps1
  Rubrik/Public/Get-RubrikVolumeGroup.ps1
  Rubrik/Public/Get-RubrikVolumeGroupMount.ps1
  Rubrik/Public/New-RubrikVolumeGroupMount.ps1
  Rubrik/Public/Remove-RubrikVolumeGroupMount.ps1
  Rubrik/Rubrik.psd1
Labels: kind-enhancement

#232 Allow the AdvancedMode to work
  Rubrik/Public/New-RubrikLogShipping.ps1
Labels: kind-bug

#235 Changed Get-RubrikAPIData.ps1
  Rubrik/Private/Get-RubrikAPIData.ps1
Labels: kind-bug
