Repository rubrikinc/rubrik-sdk-for-powershell, pull requests merged in 2019-05, with the labels that each got.

#287 New cmdlet Refresh-RubrikHost
  Rubrik/Private/Get-RubrikAPIData.ps1
  Rubrik/Public/Update-RubrikHost.ps1
  Rubrik/Rubrik.psd1
Labels: area-rcdm, exp-expert, kind-enhancement

#295 Added Custom User Agent value to HTTP headers to address issue #234
  CHANGELOG.md
  Rubrik/Public/Connect-Rubrik.ps1
  Rubrik/Rubrik.psd1
Labels: area-rcdm, exp-expert, kind-enhancement

#292 Fix docs related to #162 and others
  docs/documentation/getting_started.md
  docs/reference/Get-RubrikVM.md
Labels: area-rcdm, exp-beginner, kind-docs

#293 Change Get-RubrikOrganization to address issue 224
  CHANGELOG.md
  Rubrik/Private/Get-RubrikAPIData.ps1
  Rubrik/Rubrik.psd1
Labels: area-rcdm, exp-expert, kind-enhancement

#294 Update functions to honor -SLAID parameter to address issue #223
  CHANGELOG.md
  Rubrik/Public/Get-RubrikDatabase.ps1
  Rubrik/Public/Get-RubrikFileset.ps1
  Rubrik/Public/Get-RubrikHyperVVM.ps1
  Rubrik/Public/Get-RubrikNutanixVM.ps1
  Rubrik/Public/Get-RubrikVolumeGroup.ps1
  Rubrik/Rubrik.psd1
Labels: area-rcdm, exp-expert, kind-enhancement

#296 added primaryclusterid parameter to Get-RubrikNasShare (Issue 277)
  Rubrik/Public/Get-RubrikNASShare.ps1
Labels: kind-bug

#297 Update README to match other Build projects style
  README.md
Labels: area-rcdm, kind-docs

#299 Resolve bugs in Move-RubrikMountVMDK
  CHANGELOG.md
  Rubrik/Private/Test-DateDifference.ps1
  Rubrik/Public/Move-RubrikMountVMDK.ps1
Labels: area-rcdm, exp-expert, kind-bug
